### ISSUE TITLE
upload coverage report on codecov

### ISSUE THREAD

**Issue by deliaBlue** [zavolanlab/mirflowz#74]
The current call to upload the coverage report is:

```
      - name: submit coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./scripts/tests/
          files: .coverage
          fail_ci_if_error: true
          verbose: true
```

With a `codecov.yml` file:

```
fixes:
  - "::scripts/tests/"

codecov:
  require_ci_to_pass: true

comment:
  behavior: default
  layout: reach,diff,flags,tree,reach
  show_carryforward_flags: false

coverage:
  precision: 2
  range:
  - 60.0
  - 80.0
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include

    patch: true
    project: true
github_checks:
  annotations: true
```

With all of these, when uploading the file we obtain an "unusable report". Fix the call so a usable report is uploaded to codecov.
