### ISSUE TITLE
Write a JSON schema for the config file

### ISSUE THREAD

**Issue by deliaBlue** [zavolanlab/mirflowz#9]
Write a JSON schema for the `config` file so that the optional parameters become truly optional and the `config` file is [validated by Snakemake](https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html#validation) to be complete.

This would then be a valid MIRFLOWZ `config` file:

```yaml
samples: path/to/samples_table.csv
genome_url: path/to/gzipped/ensembl/genome.fa.gz
gtf_url: path/to/gzipped/ensembl/gene_annotations.gtf.gz
mirna_url: path/to/unzipped/mirbase/mirna_annotations.gff
map_chr_url: path/to/ucsc_ensembl_mappings.txt
```
